name: Publish Packages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Choose the package to publish'
        required: true
        options:
          - core
          - react

jobs:
  publish-core-library:
    environment: CI
    runs-on: ubuntu-latest
    if: "(github.event_name == 'workflow_dispatch' && github.event.inputs.package == 'core') || contains(github.event.head_commit.message, 'release-please--branches--main--components--cardano-connect-with-wallet-core')"
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./core
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: ⬆️ Ensure npm supports Trusted Publishing
        run: npm i -g npm@^11.5.1

      - name: 📥 Install dependencies
        run: npm ci
      - name: 📦 Bundle package
        run: npm run build
      - name: 🚀 Publish to npm (OIDC only)
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
        run: |
          unset NODE_AUTH_TOKEN NPM_TOKEN
          npm publish --provenance --access public
  publish-react-library:
    environment: CI
    runs-on: ubuntu-latest
    if: "(github.event_name == 'workflow_dispatch' && github.event.inputs.package == 'react') || contains(github.event.head_commit.message, 'release-please--branches--main--components--cardano-connect-with-wallet') && !contains(github.event.head_commit.message, 'cardano-connect-with-wallet-core')"
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./react
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - name: 📥 Install dependencies
        run: npm ci
      - name: 🧵 Install rollup
        run: npm i -g rollup
      - name: 📦 Bundle package
        run: npm run rollup
      - name: 🚀 Publish to npm (OIDC only)
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
        run: |
          unset NODE_AUTH_TOKEN NPM_TOKEN
          npm publish --provenance --access public
