name: Run Tests
on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test-react-libary:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: 🧘‍♀️ Download dependencies
        run: npm ci

      - name: 🎳 Run tests
        run: npm test
